### ISSUE TITLE
Latest version does not work the touch screen writing.

### ISSUE THREAD

**Issue by MuhametSmaili** [aml2610/react-painter#10]
Hello, there is an error, because in the latest version 0.3.9 the touch screen drawing is not working at all.
I had to return in the 0.3.8 version and there is working fine.

**Comment by aml2610** [comment]
Hi @MuhametSmaili thanks for reporting this.
It seems to be related to [this PR](https://github.com/aml2610/react-painter/pull/6/files). 

Before the PR, we were using the touches object in all cases, and in case touch screen wasn't used that object was undefined which would cause crashes.
A proper fix would probably be to look for touches object, use it if it exists, otherwise use clientX and clientY. (or similar where we check if we are using touch screen or not)

Are you interested in helping with a fix? Otherwise I'll do it.
